uploads = []
generated = []

[[outputs]]
id = "j4k3KD9gQgJKH0uMybNEA"
uri = "file://mcwilliams-media.tar.gz"
type = "unspecified"
title = "mcwilliams-media.tar.gz"

[[outputs]]
id = "c-m5S1rDOBr8p3_BcS77D"
uri = "file://mcwilliams-media-full-backup-20260513.tar.gz"
type = "unspecified"
title = "Full Backup (Source + Database) — May 13, 2026"
