// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-light/CrispWhite.tsx": () => import("../components/mockups/app-light/CrispWhite.tsx"),
  "./components/mockups/app-light/SoftSlate.tsx": () => import("../components/mockups/app-light/SoftSlate.tsx"),
  "./components/mockups/app-light/WarmSand.tsx": () => import("../components/mockups/app-light/WarmSand.tsx")
};
