// Auto-generated seed data — do not edit manually
// Format: [flag, clientName, strategist, website, hosting, seo, adwords, fbads, lsa, email, social, blog, mailbox, photo, tier, touchpoint, upsell, nextTarget, other, sortOrder]
export const MASTER_CLIENT_SEED = [
  ["","141 Peoria (Pine Ridge website)","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/7","","July 2026","",1],
  ["","3 Delta Window Films","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",2],
  ["","360+ Construction","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",3],
  ["","5th Quarter Officiating","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",4],
  ["","Accounting Outsourcing Solutions","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/7","","July 2026","",5],
  ["","Action COACH Tulsa","Tiffany",true,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",6],
  ["","Action Pest Management","Tiffany",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","Week of 7/7","Blog Add-On + Google LSA","July 2026","TK Sent proposal on 7/18 with follow-up call scheduled for 7/21",7],
  ["","Acura Neon","Tiffany",true,true,true,false,false,false,false,false,true,false,false,"Tier 1","Week of 7/7","SEO + Blog","July 2026","TK sent proposal on 7/18",8],
  ["","Adept Patriot Services","Rachelle",false,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",9],
  ["","Align Sport & Spine","Elise",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/7","","July 2026","",10],
  ["","All Dry Services, LLC","Tiffany",false,false,false,false,false,false,false,true,false,false,false,"","","","","",11],
  ["","All Dry of OKC","Tiffany",false,false,false,false,false,false,false,true,false,false,false,"Tier 1","","","","",12],
  ["","All Dry of Tulsa","Tiffany",false,false,false,false,false,false,false,true,false,false,false,"Tier 1","","","","",13],
  ["","All India Sourcing Group","Tiffany",false,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",14],
  ["","Alli Hayes Real Estate Group","Tiffany",false,false,false,false,false,false,false,true,false,false,false,"Tier 1","Week of 7/7","","July 2026","",15],
  ["","Allied Broadcasting","Tiffany",false,false,false,false,false,false,true,true,false,false,false,"Tier 2","","","","",16],
  ["","American Pipe Bending","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/7","","July 2026","",17],
  ["","AMV Exterior Contracting","Rachelle",false,true,false,false,false,false,false,false,false,false,false,"Tier 2","","","","",18],
  ["","Antiquities (Mike Withers)","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/7","","July 2026","",19],
  ["","Archer HR Consulting","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 8/19","","","",20],
  ["","Archer Insurance","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/7","","July 2026","",21],
  ["","Ark Roofing","Rachelle",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",22],
  ["","ArtsOK","Elise",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",23],
  ["","Ashes Away Chimney Sweep","Matt",false,true,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",24],
  ["","Atlas Lounge/SJS Hospitality","Tiffany",true,true,false,false,false,false,false,true,false,false,false,"Tier 1","Week of 7/21","New Website!","","Doing a one time Newsletter, won't be a monthly plan",25],
  ["","Atmos Design Build","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 8/19","","","",26],
  ["","BA Buzz","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/7","","","",27],
  ["","BAPS Foundation","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 8/19","What's your goals?","","",28],
  ["","BCB Energy Solutions","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 2","Week 7/7","Signed contract for SEO services with GMB","July 2026","",29],
  ["","Bella Vita Spa and Salon","Rachelle",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",30],
  ["","Blackwood Real Estate","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",31],
  ["","Bledsoe, Hewitt, & Gullekson","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 8/19","","","",32],
  ["","Blessings International","Rachelle",false,true,true,true,false,false,false,false,false,false,false,"Tier 3","Week of 8/19","Meeting set for 8/20","November 2025","",33],
  ["","Blue Dome Dining","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"","","","","",34],
  ["","Box Construction","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",35],
  ["","Bright Home Health","Tiffany",false,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",36],
  ["","Broken Arrow Family Dentistry","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",37],
  ["","Broken Arrow Varsity Football Booster Club","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",38],
  ["","Bruner Law Firm","Tiffany",false,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",39],
  ["","Buccal Up - Denistry for You OKC","Matt",true,true,true,false,false,false,false,true,false,false,false,"Tier 3","","","","",40],
  ["","Buccal Up Dental - Your Olathe Dentist","Matt",true,true,true,false,false,false,false,true,false,true,false,"Tier 3","","","","",41],
  ["","Buccal Up Dental- Corp","Matt",true,true,true,false,false,false,false,true,false,false,false,"Tier 3","","","","CA facebook pg checks",42],
  ["","Buccal Up Dentistry for you Broken Arrow","Matt",false,true,true,true,false,false,false,false,true,false,false,"Tier 3","","","","",43],
  ["-","Buccal Up McDougall","Matt",true,true,true,false,false,false,false,false,false,false,false,"Tier 3","","","","",44],
  ["-","Buccal Up- Denistry for You SS","Matt",false,true,true,true,false,false,false,false,true,false,false,"Tier 3","","","","",45],
  ["","CamTech","Matt",true,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",46],
  ["","Care Family Medical & Chiropractic","Matt",false,false,true,true,true,false,true,false,false,false,false,"Tier 3","","","","",47],
  ["","CFC Law","Tiffany",true,false,false,false,false,true,false,false,false,false,false,"","","","","",48],
  ["","Chapman Edge & Engine","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",49],
  ["","Child Advocacy Network","Matt",false,true,false,false,false,false,false,false,false,false,false,"","","","","",50],
  ["","Chiropractic Association","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",51],
  ["","Christian Family Institute","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",52],
  ["","Coffman & Seidenberger, PLLC","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/28","","July 2026","",53],
  ["","Cole Tech","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",54],
  ["","Colton's Support (DND)","Support",true,true,false,false,false,false,false,true,false,false,false,"Tier 2","","","","",55],
  ["","Conklin, Gilpin, Wertz","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/28","","","",56],
  ["","Core Rehab","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","Week of 7/14","","July 2026","",57],
  ["","Cornerstone FSOK","Elise",true,true,false,false,false,false,false,false,false,false,false,"","","","","",58],
  ["?","Crown Office Furnishings","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",59],
  ["","Cultivate Primary Care","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",60],
  ["?","CWC Interiors","Tiffany",true,false,false,false,false,false,false,false,false,false,false,"","","","","",61],
  ["","DMD Alarm Pro","Tiffany",true,true,true,true,false,false,true,true,false,false,false,"","","","","",62],
  ["","DomesticAide","Rachelle",true,false,true,true,false,false,false,false,false,false,false,"Tier 2","","","","",63],
  ["","Dr. Chadwick Webster DDS","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",64],
  ["","Dragonfly Enterprises (DND)","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",65],
  ["","Eagle Rock Realty & Property Management","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",66],
  ["","Eastern Oklahoma Chiropractic-Travis Ring","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",67],
  ["","Eastern Oklahoma Wellness & Chiropractic","Rachelle",true,true,true,true,false,false,false,true,false,false,false,"Tier 3","","","","",68],
  ["","Elite Home Pest Service (DND)","Rachelle",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",69],
  ["","Elite Outdoor Services LLC","Rachelle",true,true,true,true,false,false,false,false,false,true,false,"Tier 3","","","","",70],
  ["","Emerald House Design Co","Rachelle",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",71],
  ["","Emerald Quest","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",72],
  ["","Empowered Life Counseling (DND)","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",73],
  ["","Encore Coummincations","Tiffany",true,false,true,true,false,false,true,true,false,false,false,"Tier 3","","","","",74],
  ["","Envirovalve","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",75],
  ["","EOWC Medical-Rick Barnes","Rachelle",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",76],
  ["","Events By Lisa","Matt",true,false,false,false,false,false,false,false,false,false,false,"","","","","",77],
  ["","Evolution Mental Health","Rachelle",true,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",78],
  ["","Expanded Solutions","Tiffany",true,false,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",79],
  ["","Faith Tabernacle","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",80],
  ["","Floor and Restore by George","Matt",true,true,false,false,false,false,false,false,false,false,false,"","","","","",81],
  ["","Foundation Law Wesley Cherry","Matt",true,true,true,true,true,false,false,false,false,false,false,"Tier 3","","","","",82],
  ["","Frasier Law","Tiffany",true,true,true,true,false,true,false,false,true,false,false,"","","","","",83],
  ["","Fusion Enterprises LLC","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",84],
  ["","Gary W. Crews, PLLC","Rachelle",false,true,true,false,false,false,true,false,true,false,false,"Tier 3","","","","",85],
  ["","Genesis Technologies Inc.","Tiffany",true,false,false,false,false,false,false,false,false,false,false,"","","","","",86],
  ["","Good Guy's Roofing","Matt",true,false,false,false,false,false,false,false,false,false,false,"","","","","",87],
  ["","Grace and Peace Presbyterian Church","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",88],
  ["","Grassroots Essentials","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",89],
  ["","Green Country Business Solutions","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",90],
  ["","Gunter Training","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",91],
  ["","Hagen Enviromental","Matt",false,false,true,true,false,false,false,false,true,false,false,"Tier 3","","","","",92],
  ["","Harvest Acupuncture","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",93],
  ["","HBI Global Partners","Matt",true,true,true,false,false,false,false,true,false,false,false,"Tier 3","","","","",94],
  ["","Healing Broken Trust","Matt",false,false,true,true,false,false,false,false,false,false,false,"Tier 2","","","","",95],
  ["","Heritage Waste Management","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",96],
  ["","High Point Grace Church","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",97],
  ["","Hillenburg Coffee Company","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",98],
  ["","Holly Mechanical","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"","","","","",99],
  ["","Home of Grace Ministry, Inc","Elise",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",100],
  ["","Honeycomb Company of America, Inc","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",101],
  ["","Hopper Dental","Matt",true,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",102],
  ["","Integrity Pools","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",103],
  ["","Integrity Staffing Solutions","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",104],
  ["","ION Sports ☠️","Elise",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",105],
  ["","J. Miller Law Firm, PLLC","Rachelle",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",106],
  ["","Jared Haley(The Property Center)","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",107],
  ["","Joie de Vie Interiors","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",108],
  ["","Jolly Lane Lights","Tiffany",false,false,false,true,true,false,false,false,false,false,false,"Tier 2","","","","",109],
  ["","Kimberly Haar - Author","Tiffany",false,false,true,false,false,false,true,true,false,false,false,"Tier 3","","","","",110],
  ["","Kimberly K. Hays, PLLC","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",111],
  ["","Kwik Dry - Daytona","Matt",true,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",112],
  ["","Kwik Dry - Evansville","Matt",true,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",113],
  ["","Kwik Dry - Gulf Port","Matt",true,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",114],
  ["","Kwik Dry - Hampton Roads","Matt",true,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",115],
  ["","Kwik Dry - Lehigh Valley","Matt",true,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",116],
  ["","Kwik Dry - Louisville","Matt",false,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",117],
  ["","Kwik Dry - Mufreesboro","Matt",true,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",118],
  ["","Kwik Dry - OC","Matt",false,false,true,true,false,false,false,false,false,false,false,"","","","","",119],
  ["","Kwik Dry - OKC","Matt",true,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",120],
  ["","Kwik Dry - Palm Beach","Matt",false,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",121],
  ["","Kwik Dry - Phoenix","Matt",false,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",122],
  ["","Kwik Dry - LA","Matt",false,false,false,true,false,false,false,false,false,false,false,"","","","","",123],
  ["","Kwik Dry Tulsa","Matt",false,false,false,false,false,false,false,false,false,false,false,"","","","","",124],
  ["","Kwik Dry- Central Florida","Matt",false,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",125],
  ["","Kwik Dry - Rio Grande Valley","Matt",false,false,false,true,false,false,false,false,false,false,false,"","","","","",126],
  ["","L. Eads, LLC","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",127],
  ["","Lamb Homes (same owner as 141)","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",128],
  ["","Lane Publishing/Tulsa Pet (Moved Sites)","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",129],
  ["","LDC","Rachelle",false,true,false,false,false,false,true,true,true,false,false,"Tier 3","","","","FB Ad",130],
  ["","Legacy Financial & Consulting","Tiffany",false,false,false,false,false,false,false,false,false,false,false,"","","","","",131],
  ["","Legalis Connection Hub","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",132],
  ["","Len Mink Ministries","Support",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",133],
  ["","LoneStar Vapor Shop, LLC","Tiffany",false,false,true,false,false,false,true,true,false,false,false,"Tier 3","","","","",134],
  ["","M&D Contracting","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",135],
  ["","Magnolia Family Dental Care","Tiffany",true,true,true,true,false,false,false,true,false,false,false,"Tier 3","qtr strategy","","","building new site",136],
  ["","Maplebrook Acupuncture Clinc","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",137],
  ["","Mari Coffee and Tea","Rachelle",true,false,false,false,false,false,false,true,false,false,false,"Tier 1","","","","",138],
  ["","Martinez Law","Tiffany",true,true,false,true,false,false,false,false,false,false,true,"Tier 3","","","","",139],
  ["","Mathis Homes","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"","","","","",140],
  ["","MC2 Homes, LLC","Matt",false,false,true,true,false,false,false,true,false,false,false,"","","","","",141],
  ["","McDougall DDS","Matt",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",142],
  ["","McWilliams Media","Matt",false,false,true,false,false,false,true,true,true,false,false,"Tier 3","everyday","","","",143],
  ["","Monitoring America Alarm Co-Op","Rachelle",true,true,true,true,false,false,false,false,false,false,false,"Tier 3","","","","",144],
  ["","Mr Electric","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",145],
  ["","MS Moving Soulutions","Elise",true,true,false,false,false,false,false,false,false,false,false,"","","","","",146],
  ["","Nantz Mower & Small Engine LLC","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",147],
  ["","Neurogenesis Brain and Spine","Tiffany",true,false,false,false,false,false,false,false,false,false,false,"","","","","",148],
  ["","Nikki Burgett","Support",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",149],
  ["","Now Someday Adventures","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",150],
  ["","OFSA","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",151],
  ["","OK Compliance Testing Lab","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",152],
  ["","Ok Traffic Ticket Defense","Tiffany",true,true,true,true,false,false,false,false,true,false,false,"Tier 3","","","","",153],
  ["","Okieolier-Jan Collins","Support",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",154],
  ["","Oklahoma Mortgage Group","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",155],
  ["","Oklahoma Recycling Association","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",156],
  ["","Oklahome Inspections","Matt",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",157],
  ["","On The Rock","Tiffany",false,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",158],
  ["","Oren","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",159],
  ["","Pain Management of Oklahoma BA","Matt",true,true,true,true,true,false,false,true,false,false,false,"Tier 3","","","","",160],
  ["","Pain Management of Oklahoma Grove","Matt",false,false,true,true,false,false,false,false,false,false,false,"Tier 2","","","","",161],
  ["","Pain Management of Oklahoma Mcalester","Matt",false,false,true,true,false,false,false,false,false,false,false,"Tier 2","","","","",162],
  ["","Pain Management of Oklahoma Sallisaw","Matt",false,false,true,true,false,false,false,false,false,false,false,"Tier 2","","","","",163],
  ["","Pain Managmet of Oklahome Sand Springs","Matt",false,false,true,true,false,false,false,false,false,false,false,"Tier 2","","","","",164],
  ["","Petty Family Floors","Tiffany",false,false,false,false,false,false,true,false,false,false,false,"Tier 1","","","","",165],
  ["","Pharma Freedom","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",166],
  ["","Premier Janitorial","Tiffany",false,false,true,true,false,false,false,true,true,false,false,"Tier 3","","","","",167],
  ["","Premier Rheum of OK","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",168],
  ["","Precision Finishing LLC","Elise",false,false,false,false,true,false,false,false,false,false,false,"","","","","",169],
  ["","Professional Driven Solutions","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",170],
  ["","Property Arts Inc","Tiffany",false,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",171],
  ["","Pryor Creek Dental","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",172],
  ["","PSS Enterprises, Inc","Rachelle",false,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",173],
  ["","Quilter's Hideaway","Rachelle",true,false,false,false,false,false,true,false,false,false,false,"Tier 1","","","","",174],
  ["","Reimagined Health","Matt",false,false,true,false,false,false,false,true,false,false,false,"Tier 2","","","","",175],
  ["","Renaissance Reatly","Tiffany",false,false,false,false,false,false,false,true,false,false,false,"Tier 1","","","","",176],
  ["","Revitalize Osteopractic Physical Therapy","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",177],
  ["","Riverside Heat & Air","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",178],
  ["","Roof Sixty-Six Bar","Tiffany",false,false,false,true,false,false,false,false,false,false,false,"Tier 1","","","","",179],
  ["","Roofs-R-Us (DND)","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","Stopping SEO and would like to prorate the first week of June SEO and nothing more if possible. He called 6/7/2022 to cancel and ask for prorated SEO told him Matt was the decision maker and he was out of town AERODGERS",180],
  ["","Ryan's Manufacturing","Matt",true,false,false,false,false,false,false,false,false,false,false,"","","","","",181],
  ["","Sam the Concrete Man","Tiffany",false,false,false,false,false,false,false,false,false,false,true,"Tier 1","","","","New client as of 4/30",182],
  ["","Seasons OK, MO","Matt",true,false,true,true,false,false,false,true,false,false,false,"Tier 3","","","","",183],
  ["","Semi Crazy Truck Wash","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",184],
  ["","siHi Minstries","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",185],
  ["","Silver Canyon RV Park","Matt",false,false,true,true,false,false,false,true,false,false,false,"","","","","",186],
  ["","SJS Hospitality","Tiffany",false,false,true,false,false,false,false,false,false,false,false,"","","","","",187],
  ["","Southern Safe Rooms","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",188],
  ["","Southern Sheet Metal","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",189],
  ["","SpecTest LLC","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",190],
  ["","Spradlin Service Company","Rachelle",false,true,false,true,false,false,false,false,false,false,false,"Tier 2","","","","",191],
  ["","SRC Fixtures","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",192],
  ["","Standard Roofing and Contracting","Matt",false,false,true,true,false,true,false,false,false,false,false,"","","","","",193],
  ["","Starting Strength","Tiffany",false,false,false,true,false,false,true,true,false,false,false,"Tier 3","","","","",194],
  ["","Step by Step Therapy, Inc.","Tiffany",true,true,false,false,false,false,false,true,false,false,false,"Tier 2","","","","",195],
  ["","Stephen DeCanio","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",196],
  ["","Stubque","Matt",false,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",197],
  ["","SubStruct","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",198],
  ["","Sundance Office Furniture","Matt",false,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",199],
  ["","Swineheart Insurance Agency","Matt",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",200],
  ["","Tellez Heating & Air","Matt",false,false,false,true,false,false,false,false,false,false,false,"","","","","",201],
  ["","The Blanchard Law Firm","Rachelle",true,true,true,false,false,false,false,false,true,false,false,"Tier 3","","","","",202],
  ["","The Connecting Co","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"","","","","",203],
  ["","The Dental Studio of South Tulsa","Tiffany",true,true,true,false,false,false,false,false,false,false,false,"Tier 2","","","","",204],
  ["","The Office","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",205],
  ["","The Poop Fairy","Rachelle",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",206],
  ["","Thorny Nettles","Matt",true,false,false,false,false,false,false,false,false,false,false,"","","","","",207],
  ["","Tokyo Garden","Rachelle",true,true,false,false,false,false,false,true,false,false,false,"Tier 2","","","","",208],
  ["","Tower Business Complex","Rachelle",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","Linds",209],
  ["","Transcend Dental Implants & Perio","Rachelle",false,true,true,true,false,false,false,false,false,false,false,"Tier 3","","","","",210],
  ["","Truskett Law","Matt",false,true,true,false,false,false,false,true,false,false,false,"Tier 2","1/month","","","",211],
  ["","Tulsa Elite Meet","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",212],
  ["","Tulsa Executive Cleaning","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",213],
  ["","Tulsa Gun Club","Tiffany",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",214],
  ["","Tulsa Insurance Guy","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",215],
  ["","Tulsa Modern Dental","Matt",false,false,true,false,false,false,false,true,false,false,false,"","","","","",216],
  ["","Tulsa Surveillance Tech","Tiffany",true,true,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",217],
  ["","Ultimate Cabinets","Tiffany",false,false,true,true,false,false,true,true,false,false,false,"Tier 3","","","","",218],
  ["","Ultimate project, Inc","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",219],
  ["","UpClosets","Tiffany",false,false,false,true,true,false,true,true,false,false,false,"Tier 3","","","","",220],
  ["","Via Sophia Bookkeeping","Tiffany",true,false,true,false,false,false,false,false,false,false,false,"Tier 1","","","","",221],
  ["","Wagner & Lynch Law Firms","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",222],
  ["","Wagner for House","Matt",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",223],
  ["","Watson Tree Academy","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",224],
  ["","West Tulsa Tag","Tiffany",true,true,true,false,false,false,false,false,true,false,false,"Tier 1","","","","",225],
  ["","Whipp Law","Tiffany",false,false,false,false,false,false,true,false,false,false,false,"Tier 1","","","","",226],
  ["","Whitacre Glass","Rachelle",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",227],
  ["","Wiemann/IMG (DND)","Support",false,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",228],
  ["","Willow Landscape & Design","Tiffany",true,true,false,true,false,false,false,false,false,false,false,"Tier 2","","","","",229],
  ["","Winches Inc","Tiffany",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",230],
  ["","Winds of Change","Tiffany",true,true,true,false,false,false,false,true,false,false,false,"","","","","",231],
  ["","Word of Life Church","Support",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",232],
  ["","World Dental Relief","Support",true,true,false,false,false,false,false,false,false,false,false,"Tier 1","","","","",233],
  ["","ZEIDERS LAW GROUP, PLLC","Rachelle",true,true,true,true,false,false,false,false,false,false,false,"Tier 2","","","","",234]
] as const;